name: CICD

on:
  push:
    branches: [ main ]

jobs:
  generate-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   
    
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        INITIAL_VERSION: 1.0.3
        DEFAULT_BUMP: patch
        
    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}

  package-and-publish-contracts:

    runs-on: ubuntu-latest
    needs: generate-version

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/RafaelJCamara/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PUSH_NUGET }} 
        
    - name: Pack
      run: | 
        dotnet pack src/Play.Inventory.Contracts/ \
        --configuration Release \
        -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
        -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/play.inventory \
        -o packages

    - name: Publish
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.PUSH_NUGET }} --source https://nuget.pkg.github.com/RafaelJCamara/index.json
  
  build-and-deploy-service:

    runs-on: ubuntu-latest
    needs: generate-version
    
    env:
      APP_NAME: playeconomy

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        secrets: |
          "GH_OWNER=${{github.repository_owner}}"
          "GH_PAT=${{secrets.PUSH_NUGET}}"
        tags: ${{env.APP_NAME}}.azurecr.io/play.inventory:${{ needs.generate-version.outputs.new_version }}

